# Generated by Django 5.1.1 on 2024-11-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
