# Generated by Django 5.1.1 on 2024-10-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityevent_communityeventparticipant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityevent',
            old_name='title',
            new_name='name',
        ),
    ]
