# Generated by Django 5.1.1 on 2024-11-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communityinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityInvite',
        ),
    ]
