# Generated by Django 5.1.1 on 2024-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communityinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityinvite',
            old_name='Community',
            new_name='community',
        ),
    ]
