# Generated by Django 4.2.12 on 2024-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=6),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
