# Generated by Django 4.2.12 on 2024-09-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=9),
        ),
    ]
