# Generated by Django 5.1.1 on 2024-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_community_members_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
